apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: subscription1
  namespace: event-demo
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: imc01
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
