apiVersion: v1
kind: Secret
metadata:
  name: gitlabsecret
  namespace: event-demo
type: Opaque
stringData:
  # change to your gitlab user's access token with api scope
  accessToken: yZxTxxr4jKLdZE-aGj_a
  secretToken: JQ1ambOFdXGZPFWsOov0iQ
