apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafkasource-demo
  namespace: default
spec:
  consumerGroup: knative-group
  bootstrapServers:
   - my-cluster-kafka-bootstrap.kafka:9092 
  topics:
   - topic01
  sink: 
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
