# Maintainer: "MageEdu <mage@magedu.com>"
# Version: v1.0
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display-bye
  namespace: event-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: ikubernetes/event_display
          ports:
            - containerPort: 8080
